### PR TITLE
[PLATFORM-1835]: Retire prima_rs_logger

### PR DESCRIPTION
**Pull request by cpiemontese**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1835

Not sure if this is enough...

### CODE REVIEW

**Review by MaeIsBad — CHANGES_REQUESTED** [review]
You need to also install a logger. I would suggest `pretty_env_logger`

https://lib.rs/crates/pretty_env_logger

**Comment by cpiemontese** [comment]
I tried adding a docker-compose but then when building a dependency (clap_m...something) it complains rust 1.74 is needed :thinking:

**Review by MaeIsBad — APPROVED** [review]
> I tried adding a docker-compose but then when building a dependency (clap_m...something) it complains rust 1.74 is needed 🤔

not sure why you want a docker-compose, but you can just bump the rust version if you want to> I tried adding a docker-compose but then when building a dependency (clap_m...something) it complains rust 1.74 is needed 🤔

not sure why you want a docker-compose, but you can just bump the rust version if you want to

**Comment by cpiemontese** [comment]
@MaeIsBad mainly because it has a nicer interface than base `docker` + `Dockerfile`s but it's just a preference

**Comment by MaeIsBad** [comment]
For localauth0 I just do development on the host, since there aren't any other dependencies :woman_shrugging:

**Pull request merged**
